services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Mysql_@123
      MYSQL_DATABASE: ApiBarbeariaDB
      MYSQL_USER: root
      MYSQL_PASSWORD: Mysql_@123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: